<div class="gallery">
                          <div class="gallery-item" data-image="assets/img/news/img01.jpg" data-title="Image 1" href="assets/img/news/img01.jpg" title="Image 1" style="background-image: url(&quot;assets/img/news/img01.jpg&quot;);"></div>
                          <div class="gallery-item" data-image="assets/img/news/img02.jpg" data-title="Image 2" href="assets/img/news/img02.jpg" title="Image 2" style="background-image: url(&quot;assets/img/news/img02.jpg&quot;);"></div>
                          <div class="gallery-item" data-image="assets/img/news/img03.jpg" data-title="Image 3" href="assets/img/news/img03.jpg" title="Image 3" style="background-image: url(&quot;assets/img/news/img03.jpg&quot;);"></div>
                          <div class="gallery-item" data-image="assets/img/news/img04.jpg" data-title="Image 4" href="assets/img/news/img04.jpg" title="Image 4" style="background-image: url(&quot;assets/img/news/img04.jpg&quot;);"></div>
                          <div class="gallery-item" data-image="assets/img/news/img05.jpg" data-title="Image 5" href="assets/img/news/img05.jpg" title="Image 5" style="background-image: url(&quot;assets/img/news/img05.jpg&quot;);"></div>
                          <div class="gallery-item" data-image="assets/img/news/img06.jpg" data-title="Image 6" href="assets/img/news/img06.jpg" title="Image 6" style="background-image: url(&quot;assets/img/news/img06.jpg&quot;);"></div>
                          <div class="gallery-item" data-image="assets/img/news/img07.jpg" data-title="Image 7" href="assets/img/news/img07.jpg" title="Image 7" style="background-image: url(&quot;assets/img/news/img07.jpg&quot;);"></div>
                          <div class="gallery-item" data-image="assets/img/news/img08.jpg" data-title="Image 8" href="assets/img/news/img08.jpg" title="Image 8" style="background-image: url(&quot;assets/img/news/img08.jpg&quot;);"></div>
                        </div>